"""add system_config

Revision ID: 46d6ce269010
Revises: 9c7ed5614bc3
Create Date: 2026-05-04 11:22:02.312464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d6ce269010'
down_revision = '9c7ed5614bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('facebook_id'))
        batch_op.create_index(batch_op.f('ix_users_facebook_id'), ['facebook_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_facebook_id'))
        batch_op.create_index(batch_op.f('facebook_id'), ['facebook_id'], unique=True)

    # ### end Alembic commands ###
