"""add revoke_token to shared_snippets

Revision ID: 9c7ed5614bc3
Revises: 
Create Date: 2026-05-01 09:13:46.750357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7ed5614bc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoke_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_shared_snippets_revoke_token', ['revoke_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_snippets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_shared_snippets_revoke_token', type_='unique')
        batch_op.drop_column('revoke_token')

    # ### end Alembic commands ###
